# Generated by Django 4.2.6 on 2024-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('oldprice', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('Formal Shoes', 'Formal Shoes'), ('Peshawari', 'Peshawari')], max_length=200, null=True)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=200, null=True)),
            ],
        ),
    ]
