# Generated by Django 4.2.6 on 2024-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_productimage_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
