# Generated by Django 4.2.6 on 2024-02-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Formal Shoes', 'Formal Shoes'), ('Peshawari', 'Peshawari'), ('Loafers', 'Loafers'), ('Khussa', 'Khussa'), ('High Heels', 'High Heels')], max_length=200, null=True),
        ),
    ]
